<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-05T15:40:20Z" name="Default suite" finished-at="2022-06-05T15:40:20Z" duration-ms="103">
    <groups>
    </groups>
    <test started-at="2022-06-05T15:40:20Z" name="Default test" finished-at="2022-06-05T15:40:20Z" duration-ms="103">
      <class name="zoopla.uk.hookstest.ExceptionHandlingClass">
        <test-method signature="ArithmeticExceptionTest()[pri:0, instance:zoopla.uk.hookstest.ExceptionHandlingClass@503ecb24]" started-at="2022-06-05T15:40:20Z" name="ArithmeticExceptionTest" finished-at="2022-06-05T15:40:20Z" duration-ms="23" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArithmeticExceptionTest -->
      </class> <!-- zoopla.uk.hookstest.ExceptionHandlingClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
